//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AccountStrings", typeof(AccountStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınızı silmek istediğinizden emin misiniz?.
        /// </summary>
        public static string delete_confirm {
            get {
                return ResourceManager.GetString("delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabı Sil.
        /// </summary>
        public static string delete_confirmTitle {
            get {
                return ResourceManager.GetString("delete_confirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap başarıyla silindi..
        /// </summary>
        public static string delete_success {
            get {
                return ResourceManager.GetString("delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with {0}. Please enter a user name for this site below and click the Confirm button to finish logging in..
        /// </summary>
        public static string login_associateMessage {
            get {
                return ResourceManager.GetString("login_associateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} hesabınızı bağlayın..
        /// </summary>
        public static string login_associateTitle {
            get {
                return ResourceManager.GetString("login_associateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap başarıyla oluşturuldu..
        /// </summary>
        public static string login_createSuccess {
            get {
                return ResourceManager.GetString("login_createSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu e-posta adresi zaten kayıtlıdır. Lütfen başka bir e-posta adresi kullanın veya varolan hesabınızı kullanın..
        /// </summary>
        public static string login_emailExists {
            get {
                return ResourceManager.GetString("login_emailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servisle başarısız giriş..
        /// </summary>
        public static string login_failure {
            get {
                return ResourceManager.GetString("login_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarısız Giriş.
        /// </summary>
        public static string login_failureTitle {
            get {
                return ResourceManager.GetString("login_failureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foursquare kullanarak giriş yapın.
        /// </summary>
        public static string login_legend {
            get {
                return ResourceManager.GetString("login_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hesabınızı kullanarak giriş yapın.
        /// </summary>
        public static string login_message {
            get {
                return ResourceManager.GetString("login_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen hesap hiçbir işletme yönetmiyor..
        /// </summary>
        public static string login_notManager {
            get {
                return ResourceManager.GetString("login_notManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydol.
        /// </summary>
        public static string login_registerTitle {
            get {
                return ResourceManager.GetString("login_registerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yap.
        /// </summary>
        public static string login_title {
            get {
                return ResourceManager.GetString("login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ile giriş yap.
        /// </summary>
        public static string login_title2 {
            get {
                return ResourceManager.GetString("login_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı ismi zaten var. Lütfen başka bir kullanıcı ismi girin.
        /// </summary>
        public static string login_usernameExists {
            get {
                return ResourceManager.GetString("login_usernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba.
        /// </summary>
        public static string loginpartial_hello {
            get {
                return ResourceManager.GetString("loginpartial_hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string loginpartial_login {
            get {
                return ResourceManager.GetString("loginpartial_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string loginpartial_logoff {
            get {
                return ResourceManager.GetString("loginpartial_logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabı Sil.
        /// </summary>
        public static string manage_delete {
            get {
                return ResourceManager.GetString("manage_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabı Sil.
        /// </summary>
        public static string manage_deleteTitle {
            get {
                return ResourceManager.GetString("manage_deleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Detaylarını Yönet.
        /// </summary>
        public static string manage_detailsTitle {
            get {
                return ResourceManager.GetString("manage_detailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yapmış olan hesap.
        /// </summary>
        public static string manage_message {
            get {
                return ResourceManager.GetString("manage_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Subscriptions.
        /// </summary>
        public static string manage_subsTitle {
            get {
                return ResourceManager.GetString("manage_subsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabı yönet.
        /// </summary>
        public static string manage_title {
            get {
                return ResourceManager.GetString("manage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string manage_update {
            get {
                return ResourceManager.GetString("manage_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foursquare&apos;da göster.
        /// </summary>
        public static string manage_viewFsq {
            get {
                return ResourceManager.GetString("manage_viewFsq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu hatayı düzeltmek için ,aşağıdaki butona basıp Foursquare&apos;a gidin ve işletme sahibi olan bir hesapla giriş yapın..
        /// </summary>
        public static string mistake_instructions1 {
            get {
                return ResourceManager.GetString("mistake_instructions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayrıca işletme hesabınız yerine kişisel hesabınızla giriş yaptığınızdan emin olun..
        /// </summary>
        public static string mistake_instructions2 {
            get {
                return ResourceManager.GetString("mistake_instructions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğer hala bu hatayı görüyorsanız , işletme sahibi olarak kayıtlı olmadığınız anlamına gelir. Daha fazla bilgi için lütfen bu linke göz atın:.
        /// </summary>
        public static string mistake_instructions3 {
            get {
                return ResourceManager.GetString("mistake_instructions3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Hatası.
        /// </summary>
        public static string mistake_title {
            get {
                return ResourceManager.GetString("mistake_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir Yönetici Hesabıyla Giriş Yapmalısınız..
        /// </summary>
        public static string mistake_title2 {
            get {
                return ResourceManager.GetString("mistake_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta Adresi.
        /// </summary>
        public static string Register_EmailAddress {
            get {
                return ResourceManager.GetString("Register_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir e-posta adresi girin.
        /// </summary>
        public static string Register_EmailAddress_Required {
            get {
                return ResourceManager.GetString("Register_EmailAddress_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir e-posta adresi girin.
        /// </summary>
        public static string Register_EmailAddressInvalid {
            get {
                return ResourceManager.GetString("Register_EmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu hesap tarafından yönetilen işletmeler.
        /// </summary>
        public static string Register_ManagedVenues {
            get {
                return ResourceManager.GetString("Register_ManagedVenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon numarası.
        /// </summary>
        public static string Register_PhoneNumber {
            get {
                return ResourceManager.GetString("Register_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir telefon numarası girin.
        /// </summary>
        public static string Register_PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("Register_PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı İsmi.
        /// </summary>
        public static string Register_UserName {
            get {
                return ResourceManager.GetString("Register_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir kullanıcı ismi girin.
        /// </summary>
        public static string Register_UserName_Required {
            get {
                return ResourceManager.GetString("Register_UserName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu e-posta adresi zaten kayıtlıdır. Lütfen başka bir e-posta adresi kullanın veya varolan hesabınızı kullanın..
        /// </summary>
        public static string update_emailExists {
            get {
                return ResourceManager.GetString("update_emailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap başarıyla güncellendi.
        /// </summary>
        public static string update_successMessage {
            get {
                return ResourceManager.GetString("update_successMessage", resourceCulture);
            }
        }
    }
}
