//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.HomeStrings", typeof(HomeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farklı tasarımları olan Countify&apos;ı işletmenizin duvarına asarak veya masa üzerinde kullanabilirsiniz..
        /// </summary>
        public static string businessString {
            get {
                return ResourceManager.GetString("businessString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTIFY&apos;I.
        /// </summary>
        public static string businessTitle1 {
            get {
                return ResourceManager.GetString("businessTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İŞLETMENE YERLEŞTİR.
        /// </summary>
        public static string businessTitle2 {
            get {
                return ResourceManager.GetString("businessTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countify, işletmenizin sosyal medyadaki değerini hayatımızın içine yansıtarak, bu değeri bir pazarlama aracı olarak kullanmanızı sağlar..
        /// </summary>
        public static string cafeString {
            get {
                return ResourceManager.GetString("cafeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countify, bir pazarlama aracı olmasının yanında; işletmenizde yer almasını isteyeceğiniz bir ürün olarak sizin için tasarlandı..
        /// </summary>
        public static string counterString {
            get {
                return ResourceManager.GetString("counterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countify, onaylanmış beğeni olgusunu gerçek hayata yansıtarak müşteri sayınızı arttırırken, kendini sürekli güncelleyen yapısı sayesinde sizinle müşterileriniz arasında interaktif bir ortam yaratır..
        /// </summary>
        public static string customerString {
            get {
                return ResourceManager.GetString("customerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖLÇÜLER:.
        /// </summary>
        public static string dimensions {
            get {
                return ResourceManager.GetString("dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTIFY DENEYİMİ.
        /// </summary>
        public static string experienceTitle {
            get {
                return ResourceManager.GetString("experienceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countify&apos;ı satın aldıktan sonra, ek olarak aylık müşteri analiz raporunu satın alabilir, müşteri profilinizi daha iyi anlayabilir ve gelirinizi arttırabilirsiniz..
        /// </summary>
        public static string graphString {
            get {
                return ResourceManager.GetString("graphString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASIL ÇALIŞIR.
        /// </summary>
        public static string howWorks {
            get {
                return ResourceManager.GetString("howWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol Paneli.
        /// </summary>
        public static string menu_controlPanel {
            get {
                return ResourceManager.GetString("menu_controlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countify Deneyimi.
        /// </summary>
        public static string menu_experience {
            get {
                return ResourceManager.GetString("menu_experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasıl Çalışır?.
        /// </summary>
        public static string menu_howWorks {
            get {
                return ResourceManager.GetString("menu_howWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string menu_login {
            get {
                return ResourceManager.GetString("menu_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ön Sipariş.
        /// </summary>
        public static string menu_order {
            get {
                return ResourceManager.GetString("menu_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖN SİPARİŞ VER.
        /// </summary>
        public static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SADECE PRİZE.
        /// </summary>
        public static string outlet1 {
            get {
                return ResourceManager.GetString("outlet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAK!.
        /// </summary>
        public static string outlet2 {
            get {
                return ResourceManager.GetString("outlet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi aktarımı için WI-FI bağlantısı gereklidir..
        /// </summary>
        public static string wifiString {
            get {
                return ResourceManager.GetString("wifiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WI-FI.
        /// </summary>
        public static string wifiTitle1 {
            get {
                return ResourceManager.GetString("wifiTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAĞLANTISI KUR.
        /// </summary>
        public static string wifiTitle2 {
            get {
                return ResourceManager.GetString("wifiTitle2", resourceCulture);
            }
        }
    }
}
