//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LayoutStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LayoutStrings", typeof(LayoutStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bir.
        /// </summary>
        public static string footer_a {
            get {
                return ResourceManager.GetString("footer_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2014 Innovaction | All rights reserved..
        /// </summary>
        public static string footer_copyright {
            get {
                return ResourceManager.GetString("footer_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projesidir.
        /// </summary>
        public static string footer_project {
            get {
                return ResourceManager.GetString("footer_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol Paneli.
        /// </summary>
        public static string nav_controlPanel {
            get {
                return ResourceManager.GetString("nav_controlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string nav_home {
            get {
                return ResourceManager.GetString("nav_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişler.
        /// </summary>
        public static string nav_orders {
            get {
                return ResourceManager.GetString("nav_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string nav_subs {
            get {
                return ResourceManager.GetString("nav_subs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yöneticiler.
        /// </summary>
        public static string nav_users {
            get {
                return ResourceManager.GetString("nav_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşletmeler.
        /// </summary>
        public static string nav_venues {
            get {
                return ResourceManager.GetString("nav_venues", resourceCulture);
            }
        }
    }
}
