//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.OrderStrings", typeof(OrderStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişler.
        /// </summary>
        public static string index_title {
            get {
                return ResourceManager.GetString("index_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Telefon Numaranızı veya E-posta Adresinizi Belirtiniz.
        /// </summary>
        public static string new_emailOrPhone {
            get {
                return ResourceManager.GetString("new_emailOrPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GONDER.
        /// </summary>
        public static string new_submit {
            get {
                return ResourceManager.GetString("new_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string PreOrderModel_Address {
            get {
                return ResourceManager.GetString("PreOrderModel_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsletme adi.
        /// </summary>
        public static string PreOrderModel_BusinessName {
            get {
                return ResourceManager.GetString("PreOrderModel_BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşletme Adı Kısmını Doldurmanız Gereklidir..
        /// </summary>
        public static string PreOrderModel_BusinessNameRequired {
            get {
                return ResourceManager.GetString("PreOrderModel_BusinessNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta.
        /// </summary>
        public static string PreOrderModel_Email {
            get {
                return ResourceManager.GetString("PreOrderModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Geçerli Bir E-Posta Adresi Giriniz..
        /// </summary>
        public static string PreOrderModel_EmailInvalid {
            get {
                return ResourceManager.GetString("PreOrderModel_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajiniz.
        /// </summary>
        public static string PreOrderModel_Message {
            get {
                return ResourceManager.GetString("PreOrderModel_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        public static string PreOrderModel_Name {
            get {
                return ResourceManager.GetString("PreOrderModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad – Soyad Kısımını Doldurmanız Gereklidir..
        /// </summary>
        public static string PreOrderModel_NameRequired {
            get {
                return ResourceManager.GetString("PreOrderModel_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string PreOrderModel_Phone {
            get {
                return ResourceManager.GetString("PreOrderModel_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teşekkürler! Ürün talebiniz elimize ulaştı. Mümkün olduğunca çabuk sizinle iletişime geçeceğiz..
        /// </summary>
        public static string success_message {
            get {
                return ResourceManager.GetString("success_message", resourceCulture);
            }
        }
    }
}
