//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.StatStrings", typeof(StatStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşletmenizin Foursquare check-in grafiği:.
        /// </summary>
        public static string ChartDescription {
            get {
                return ResourceManager.GetString("ChartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol Paneli.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol Paneli görüntülenemiyor:İşletme numarası geçersiz.
        /// </summary>
        public static string InvalidVenueId {
            get {
                return ResourceManager.GetString("InvalidVenueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol panelini görmek için Foursquare üzerinde en az bir işletmenin sahibi olmalısınız.Eğer zaten bir işletmenin sahibiyseniz , bu sorunu gidermek için çıkış yapıp tekrar deneyiniz..
        /// </summary>
        public static string NoManagedVenues {
            get {
                return ResourceManager.GetString("NoManagedVenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seç.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstatistiklerini görmek istediğiniz işletmeyi seçiniz:.
        /// </summary>
        public static string SelectVenueText {
            get {
                return ResourceManager.GetString("SelectVenueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetmediğiniz işletmenin kontrol panelini göremezsiniz.
        /// </summary>
        public static string VenueNotManaged {
            get {
                return ResourceManager.GetString("VenueNotManaged", resourceCulture);
            }
        }
    }
}
